### PR TITLE
Offering a more verbose presentation

### PR DESCRIPTION
**Pull request by paladhammika**
I hope you find these commits beneficial. 

By the way, this site is quite nice. I certainly prefer the lightweight interface as opposed to SuttaCentral.

### CODE REVIEW

**Comment by thesunshade** [comment]
Thanks!

This was my first PR from a "stranger on the internet". I'm going to make a few changes to the layout, but you have given me a really good start. Thank you. Godak Pin!

**Comment by thesunshade** [comment]
OK! I got the clicking thing to work.

Please let me know if you have any feedback.

**Comment by paladhammika** [comment]
What you've added is great. Thanks. My only concern is that having no ToC/navigation might present a barrier of entry for many people though I can certainly manage. 

I can help with html input but javascript is completely foreign to me.

**Comment by thesunshade** [comment]
> My only concern is that having no ToC/navigation might present a barrier of entry

Right. This interface was honestly just a way for me to figure out how to fetch the data and present it. And in doing so I realized that it could all be done in less than 5kb, so I stuck with that.

Personally, I am rarely needing to navigate to get to what I want. I'm either searching (which of course this app can't do) or I use my [name lookup tool](https://name.readingfaithfully.org/). But often I know the citation. This interface then allows a way to get to the suttas with a few keystrokes instead of having to drill down. And sometimes even knowing the citation doesn't help in in that drill-down process. 

And interfaces are hard! I'm the one who designed the ReadingFaithfully.org interface. It's not perfect either, but it tries to make the suttas more accessible. 

I only started learning js about 9 months ago. I can't claim that it was an ideal investment of time, but knowing as much as I do has allowed me to do a bunch of fun stuff and solve problems I couldn't before. If you have the free time and resources, it's something you could certainly learn.

Thanks for the feedback!

**Pull request merged**
